version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress2
    depends_on:
      - db
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: shiva
      WORDPRESS_DB_PASSWORD: shiva123
      WORDPRESS_DB_NAME: wordpressdb
    volumes:
      - wordpress_data:/var/www/html

  db:
    image: mysql:5.7
    container_name: wordpress_db2
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpressdb
      MYSQL_USER: shiva
      MYSQL_PASSWORD: shiva123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  wordpress_data:
  db_data:
